//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookids
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaboracoes
    {
        public int IdAnimador { get; set; }
        public int NrEventos { get; set; }
    
        public virtual Animadores Animadores { get; set; }
        public virtual Eventos Eventos { get; set; }

        public override string ToString()
        {
            return "ID: " + Animadores.IdPessoa + " - Nome: " + Animadores.Nome; 
        }
    }
}
