//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookids
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compras()
        {
            this.DetalheCompras = new HashSet<DetalheCompras>();
        }
    
        public int NrCompra { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime Data { get; set; }
        public bool UtilizouCartao { get; set; }

        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalheCompras> DetalheCompras { get; set; }

        public decimal getTotalCompra()
        {
            decimal total = 0;
            foreach(DetalheCompras dc in DetalheCompras)
            {
                total += dc.getTotalDetalhe();
            }
            return total;
        }

        public string getFatura(Clientes cliente, Compras compra)
        {
            
            string descricao = "Compra nº: " + compra.NrCompra + " \n " + cliente.Nome + "\n Nº Cartão: " + cliente.NrCartao
                + "\n________________________________________________________________________________________"
                + "\nCompra efetuada a " + compra.Data.ToString("dd/MM/yyyy") + " às " + compra.Data.ToString("HH:mm:ss");
            foreach (DetalheCompras dc in DetalheCompras)
            { 
                descricao += "\n - " + string.Format("{0} ({1})- {2:F2}/uni", dc.Produtos.Designacao, dc.Quantidade, dc.Produtos.Preco);
            }
            descricao += "\n________________________________________________________________________________________" +
            string.Format("\nTotal da Compra: €{0:F2}", compra.getTotalCompra());

            return descricao;
            
        }
    }
}
