//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookids
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalheCompras
    {
        public int Quantidade { get; set; }
        public int NrCompra { get; set; }
        public int CodProduto { get; set; }
    
        public virtual Compras Compras { get; set; }
        public virtual Produtos Produtos { get; set; }

        public override string ToString()
        {
            return Produtos.Designacao + ": " + Quantidade;
        }

        public decimal getTotalDetalhe()
        {
            decimal total = Produtos.Preco * Quantidade;
            
            return total;
        }
    }

}
