//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookids
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participacoes
    {
        public int IdEscola { get; set; }
        public int NrEvento { get; set; }
    
        public virtual Escolas Escolas { get; set; }
        public virtual Eventos Eventos { get; set; }

        public override string ToString()
        {
            return Escolas.Nome + " (" + Escolas.Localidade + ")";
        }
    }
}
