//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookids
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalheCompras
    {
        public string Quantidade { get; set; }
        public int ComprasNrCompra { get; set; }
        public int ProdutosCodProduto { get; set; }
    
        public virtual Compras Compras { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
